# Generated by Django 2.1 on 2019-12-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_post_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('contents', models.TextField(max_length=1000, verbose_name='contents')),
                ('date', models.CharField(max_length=255, verbose_name='年月日など')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='image（任意）')),
            ],
        ),
    ]
