# Generated by Django 2.1 on 2019-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20191225_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=255, verbose_name='username')),
                ('password', models.CharField(default='password', max_length=10, verbose_name='password')),
            ],
        ),
    ]
