# Generated by Django 2.1 on 2019-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=6, upload_to='upload/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
