# Generated by Django 2.1 on 2019-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='contents',
            field=models.TextField(default=999, max_length=1000, verbose_name='contents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=999, upload_to='upload/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=999, max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=999, verbose_name='url'),
            preserve_default=False,
        ),
    ]
