# Generated by Django 2.1 on 2019-12-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20191223_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tools',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='使用言語・ツール（複数ある場合はカンマで区切って入力）'),
        ),
    ]
