# Generated by Django 2.1 on 2019-12-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_postactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='postactivity',
            name='category',
            field=models.CharField(choices=[('', ' カテゴリーを選んでください '), ('0', '研究'), ('1', '学校生活'), ('2', 'その他')], default=1, max_length=255, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='contents',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='contents（任意）'),
        ),
    ]
