# Generated by Django 2.1 on 2019-12-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20191229_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postactivity',
            name='image',
        ),
    ]
